name: Deploy Topupnow app

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and tag the Docker image
        id: build-image
        env:
          ECR_REGISTRY: 267602022023.dkr.ecr.us-east-1.amazonaws.com/personal-ecr
          IMAGE_NAME: hello-world
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:${GITHUB_SHA::8} .
          echo "::set-output name=image-uri::$ECR_REGISTRY/$IMAGE_NAME:${GITHUB_SHA::8}"
      
      - name: Push the Docker image to ECR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.build-image.outputs.image-uri }}